Line_2 $$ private void doFail(String newName, String message) -->Line_9 $$ fail("No exception was thrown")[ CD ]
Line_2 $$ private void doFail(String newName, String message) -->Line_4 $$ doTest(newName)[ FD ]
Line_2 $$ private void doFail(String newName, String message) -->Line_6 $$ assertEquals(message, e.getMessage())[ FD ]
