Line_5 $$ ExceptionEventListener listener = this.context.getBean(ExceptionEventListener.class)-->Line_6 $$ this.eventCollector.assertNoEventReceived(listener)[ FD ]
Line_2 $$ public void exceptionPropagated() -->Line_4 $$ TestEvent event = new TestEvent(this, "fail")[ CD ]
Line_5 $$ ExceptionEventListener listener = this.context.getBean(ExceptionEventListener.class)-->Line_12 $$ this.eventCollector.assertEvent(listener, event)[ FD ]
Line_2 $$ public void exceptionPropagated() -->Line_5 $$ ExceptionEventListener listener = this.context.getBean(ExceptionEventListener.class)[ CD ]
Line_4 $$ TestEvent event = new TestEvent(this, "fail")-->Line_12 $$ this.eventCollector.assertEvent(listener, event)[ FD ]
Line_2 $$ public void exceptionPropagated() -->Line_6 $$ this.eventCollector.assertNoEventReceived(listener)[ CD ]
Line_2 $$ public void exceptionPropagated() -->Line_3 $$ load(ExceptionEventListener.class)[ CD ]
Line_4 $$ TestEvent event = new TestEvent(this, "fail")-->Line_8 $$ this.context.publishEvent(event)[ FD ]
