Line_27 $$ throwable = throwable.getCause()-->Line_29 $$ Assert.assertEquals(RuntimeExceptionProcessCallable.class.getName(), throwable.getMessage())[ FD ]
Line_2 $$ public void testException() throws Exception -->Line_18 $$ future = processChannel.getProcessNoticeableFuture()[ CD ]
Line_5 $$ Future<Serializable> future = processChannel.getProcessNoticeableFuture()-->Line_23 $$ Assert.assertFalse(future.isCancelled())[ FD ]
Line_3 $$ DummyExceptionProcessCallable dummyExceptionProcessCallable = new DummyExceptionProcessCallable()-->Line_4 $$ ProcessChannel<Serializable> processChannel = _localProcessExecutor.execute(_createJPDAProcessConfig(_JPDA_OPTIONS1), dummyExceptionProcessCallable)[ FD ]
Line_2 $$ public void testException() throws Exception -->Line_4 $$ ProcessChannel<Serializable> processChannel = _localProcessExecutor.execute(_createJPDAProcessConfig(_JPDA_OPTIONS1), dummyExceptionProcessCallable)[ CD ]
Line_2 $$ public void testException() throws Exception -->Line_5 $$ Future<Serializable> future = processChannel.getProcessNoticeableFuture()[ CD ]
Line_18 $$ future = processChannel.getProcessNoticeableFuture()-->Line_23 $$ Assert.assertFalse(future.isCancelled())[ FD ]
Line_16 $$ RuntimeExceptionProcessCallable runtimeExceptionProcessCallable = new RuntimeExceptionProcessCallable()-->Line_17 $$ processChannel = _localProcessExecutor.execute(_createJPDAProcessConfig(_JPDA_OPTIONS1), runtimeExceptionProcessCallable)[ FD ]
Line_27 $$ throwable = throwable.getCause()-->Line_28 $$ Assert.assertSame(RuntimeException.class, throwable.getClass())[ FD ]
Line_12 $$ Throwable throwable = ee.getCause()-->Line_14 $$ Assert.assertEquals(DummyExceptionProcessCallable.class.getName(), throwable.getMessage())[ FD ]
Line_18 $$ future = processChannel.getProcessNoticeableFuture()-->Line_20 $$ future.get()[ FD ]
Line_5 $$ Future<Serializable> future = processChannel.getProcessNoticeableFuture()-->Line_10 $$ Assert.assertFalse(future.isCancelled())[ FD ]
Line_12 $$ Throwable throwable = ee.getCause()-->Line_29 $$ Assert.assertEquals(RuntimeExceptionProcessCallable.class.getName(), throwable.getMessage())[ FD ]
Line_17 $$ processChannel = _localProcessExecutor.execute(_createJPDAProcessConfig(_JPDA_OPTIONS1), runtimeExceptionProcessCallable)-->Line_18 $$ future = processChannel.getProcessNoticeableFuture()[ FD ]
Line_2 $$ public void testException() throws Exception -->Line_3 $$ DummyExceptionProcessCallable dummyExceptionProcessCallable = new DummyExceptionProcessCallable()[ CD ]
Line_12 $$ Throwable throwable = ee.getCause()-->Line_26 $$ Assert.assertSame(ProcessException.class, throwable.getClass())[ FD ]
Line_5 $$ Future<Serializable> future = processChannel.getProcessNoticeableFuture()-->Line_20 $$ future.get()[ FD ]
Line_12 $$ Throwable throwable = ee.getCause()-->Line_27 $$ throwable = throwable.getCause()[ FD ]
Line_2 $$ public void testException() throws Exception -->Line_17 $$ processChannel = _localProcessExecutor.execute(_createJPDAProcessConfig(_JPDA_OPTIONS1), runtimeExceptionProcessCallable)[ CD ]
Line_5 $$ Future<Serializable> future = processChannel.getProcessNoticeableFuture()-->Line_18 $$ future = processChannel.getProcessNoticeableFuture()[ FD ]
Line_4 $$ ProcessChannel<Serializable> processChannel = _localProcessExecutor.execute(_createJPDAProcessConfig(_JPDA_OPTIONS1), dummyExceptionProcessCallable)-->Line_5 $$ Future<Serializable> future = processChannel.getProcessNoticeableFuture()[ FD ]
Line_18 $$ future = processChannel.getProcessNoticeableFuture()-->Line_24 $$ Assert.assertTrue(future.isDone())[ FD ]
Line_5 $$ Future<Serializable> future = processChannel.getProcessNoticeableFuture()-->Line_24 $$ Assert.assertTrue(future.isDone())[ FD ]
Line_4 $$ ProcessChannel<Serializable> processChannel = _localProcessExecutor.execute(_createJPDAProcessConfig(_JPDA_OPTIONS1), dummyExceptionProcessCallable)-->Line_17 $$ processChannel = _localProcessExecutor.execute(_createJPDAProcessConfig(_JPDA_OPTIONS1), runtimeExceptionProcessCallable)[ FD ]
Line_12 $$ Throwable throwable = ee.getCause()-->Line_13 $$ Assert.assertSame(ProcessException.class, throwable.getClass())[ FD ]
Line_2 $$ public void testException() throws Exception -->Line_16 $$ RuntimeExceptionProcessCallable runtimeExceptionProcessCallable = new RuntimeExceptionProcessCallable()[ CD ]
Line_12 $$ Throwable throwable = ee.getCause()-->Line_28 $$ Assert.assertSame(RuntimeException.class, throwable.getClass())[ FD ]
Line_4 $$ ProcessChannel<Serializable> processChannel = _localProcessExecutor.execute(_createJPDAProcessConfig(_JPDA_OPTIONS1), dummyExceptionProcessCallable)-->Line_18 $$ future = processChannel.getProcessNoticeableFuture()[ FD ]
Line_5 $$ Future<Serializable> future = processChannel.getProcessNoticeableFuture()-->Line_7 $$ future.get()[ FD ]
Line_5 $$ Future<Serializable> future = processChannel.getProcessNoticeableFuture()-->Line_11 $$ Assert.assertTrue(future.isDone())[ FD ]
