Line_4 $$ FutureTask<Exception> futureTask = new FutureTask<Exception>(new Callable<Exception>() -->Line_11 $$ return null[ CD ]
Line_2 $$ public void testNew10() throws Exception -->Line_16 $$ Exception exception = futureTask.get()[ CD ]
Line_2 $$ public void testNew10() throws Exception -->Line_3 $$ final ClassLoader classLoader = getClass().getClassLoader()[ CD ]
Line_2 $$ public void testNew10() throws Exception -->Line_15 $$ thread.start()[ CD ]
Line_4 $$ FutureTask<Exception> futureTask = new FutureTask<Exception>(new Callable<Exception>() -->Line_16 $$ Exception exception = futureTask.get()[ FD ]
Line_3 $$ final ClassLoader classLoader = getClass().getClassLoader()-->Line_7 $$ Thread.currentThread().setContextClassLoader(classLoader)[ FD ]
Line_2 $$ public void testNew10() throws Exception -->Line_18 $$ Assert.assertTrue(exception instanceof SecurityException)[ CD ]
Line_2 $$ public void testNew10() throws Exception -->Line_4 $$ FutureTask<Exception> futureTask = new FutureTask<Exception>(new Callable<Exception>() [ CD ]
Line_2 $$ public void testNew10() throws Exception -->Line_17 $$ Assert.assertNotNull(exception)[ CD ]
