Line_2 $$ private void onProcessStop(ExecResult execResult) -->Line_3 $$ lock.lock()[ CD ]
Line_2 $$ private void onProcessStop(ExecResult execResult) -->Line_6 $$ execResult.rethrowFailure().assertNormalExitValue()[ FD ]
