Line_2 $$ public void handleExceptionInOurTx(InterceptorContext invocation, Throwable t, Transaction tx, final EJBComponent component) throws Exception -->Line_14 $$ if (t instanceof RuntimeException) [ FD ]
Line_2 $$ public void handleExceptionInOurTx(InterceptorContext invocation, Throwable t, Transaction tx, final EJBComponent component) throws Exception -->Line_20 $$ setRollbackOnly(tx)[ CD ]
Line_10 $$ if (t instanceof Error) -->Line_14 $$ if (t instanceof RuntimeException) [ CD ]
Line_2 $$ public void handleExceptionInOurTx(InterceptorContext invocation, Throwable t, Transaction tx, final EJBComponent component) throws Exception -->Line_10 $$ if (t instanceof Error) [ FD ]
Line_9 $$ if (!(t instanceof EJBException || t instanceof RemoteException)) -->Line_10 $$ if (t instanceof Error) [ CD ]
Line_2 $$ public void handleExceptionInOurTx(InterceptorContext invocation, Throwable t, Transaction tx, final EJBComponent component) throws Exception -->Line_9 $$ if (!(t instanceof EJBException || t instanceof RemoteException)) [ CD ]
Line_2 $$ public void handleExceptionInOurTx(InterceptorContext invocation, Throwable t, Transaction tx, final EJBComponent component) throws Exception -->Line_15 $$ t = new EJBException((Exception) t)[ FD ]
Line_10 $$ if (t instanceof Error) -->Line_11 $$ Throwable cause = t[ CD ]
Line_2 $$ public void handleExceptionInOurTx(InterceptorContext invocation, Throwable t, Transaction tx, final EJBComponent component) throws Exception -->Line_6 $$ setRollbackOnly(tx)[ FD ]
Line_12 $$ t = EjbLogger.ROOT_LOGGER.unexpectedError()-->Line_14 $$ if (t instanceof RuntimeException) [ FD ]
Line_4 $$ if (ae != null) -->Line_5 $$ if (ae.isRollback())[ CD ]
Line_10 $$ if (t instanceof Error) -->Line_13 $$ t.initCause(cause)[ CD ]
Line_5 $$ if (ae.isRollback())-->Line_6 $$ setRollbackOnly(tx)[ CD ]
Line_2 $$ public void handleExceptionInOurTx(InterceptorContext invocation, Throwable t, Transaction tx, final EJBComponent component) throws Exception -->Line_13 $$ t.initCause(cause)[ FD ]
Line_2 $$ public void handleExceptionInOurTx(InterceptorContext invocation, Throwable t, Transaction tx, final EJBComponent component) throws Exception -->Line_20 $$ setRollbackOnly(tx)[ FD ]
Line_14 $$ if (t instanceof RuntimeException) -->Line_15 $$ t = new EJBException((Exception) t)[ CD ]
Line_2 $$ public void handleExceptionInOurTx(InterceptorContext invocation, Throwable t, Transaction tx, final EJBComponent component) throws Exception -->Line_3 $$ ApplicationExceptionDetails ae = component.getApplicationException(t.getClass(), invocation.getMethod())[ CD ]
Line_12 $$ t = EjbLogger.ROOT_LOGGER.unexpectedError()-->Line_13 $$ t.initCause(cause)[ FD ]
Line_3 $$ ApplicationExceptionDetails ae = component.getApplicationException(t.getClass(), invocation.getMethod())-->Line_5 $$ if (ae.isRollback())[ FD ]
Line_2 $$ public void handleExceptionInOurTx(InterceptorContext invocation, Throwable t, Transaction tx, final EJBComponent component) throws Exception -->Line_12 $$ t = EjbLogger.ROOT_LOGGER.unexpectedError()[ FD ]
Line_3 $$ ApplicationExceptionDetails ae = component.getApplicationException(t.getClass(), invocation.getMethod())-->Line_4 $$ if (ae != null) [ FD ]
Line_12 $$ t = EjbLogger.ROOT_LOGGER.unexpectedError()-->Line_15 $$ t = new EJBException((Exception) t)[ FD ]
Line_11 $$ Throwable cause = t-->Line_13 $$ t.initCause(cause)[ FD ]
Line_2 $$ public void handleExceptionInOurTx(InterceptorContext invocation, Throwable t, Transaction tx, final EJBComponent component) throws Exception -->Line_3 $$ ApplicationExceptionDetails ae = component.getApplicationException(t.getClass(), invocation.getMethod())[ FD ]
Line_10 $$ if (t instanceof Error) -->Line_12 $$ t = EjbLogger.ROOT_LOGGER.unexpectedError()[ CD ]
Line_2 $$ public void handleExceptionInOurTx(InterceptorContext invocation, Throwable t, Transaction tx, final EJBComponent component) throws Exception -->Line_4 $$ if (ae != null) [ CD ]
