Line_2 $$ private void shouldThrow(Class<? extends Exception> ecls, Runnable runnable) -->Line_6 $$ assertSame(ecls, e.getClass())[ FD ]
Line_2 $$ private void shouldThrow(Class<? extends Exception> ecls, Runnable runnable) -->Line_10 $$ assertTrue("Should've thrown " + ecls.getSimpleName(), false)[ CD ]
Line_2 $$ private void shouldThrow(Class<? extends Exception> ecls, Runnable runnable) -->Line_10 $$ assertTrue("Should've thrown " + ecls.getSimpleName(), false)[ FD ]
Line_2 $$ private void shouldThrow(Class<? extends Exception> ecls, Runnable runnable) -->Line_4 $$ runnable.run()[ FD ]
