Line_5 $$ ErrorAsyncDatagramReceiveHandler errorAsyncDatagramReceiveHandler = new ErrorAsyncDatagramReceiveHandler()-->Line_6 $$ errorAsyncDatagramReceiveHandler.receive(null, null)[ FD ]
Line_8 $$ LogRecord logRecord = logRecords.get(0)-->Line_9 $$ Assert.assertEquals("Unable to dispatch", logRecord.getMessage())[ FD ]
Line_8 $$ LogRecord logRecord = logRecords.get(0)-->Line_10 $$ Throwable throwable = logRecord.getThrown()[ FD ]
Line_4 $$ List<LogRecord> logRecords = captureHandler.getLogRecords()-->Line_7 $$ Assert.assertEquals(1, logRecords.size())[ FD ]
Line_4 $$ List<LogRecord> logRecords = captureHandler.getLogRecords()-->Line_8 $$ LogRecord logRecord = logRecords.get(0)[ FD ]
Line_3 $$ try (CaptureHandler captureHandler = JDKLoggerTestUtil.configureJDKLogger(BaseAsyncDatagramReceiveHandler.class.getName(), Level.SEVERE)) -->Line_4 $$ List<LogRecord> logRecords = captureHandler.getLogRecords()[ FD ]
Line_10 $$ Throwable throwable = logRecord.getThrown()-->Line_11 $$ Assert.assertEquals(Exception.class, throwable.getClass())[ FD ]
