Line_2 $$ public synchronized void testFailure(Failure failure) throws Exception -->Line_5 $$ final Throwable cause = throwable.getCause()[ CD ]
Line_4 $$ final Throwable throwable = failure.getException()-->Line_6 $$ if (ComparisonFailureData.isAssertionError(throwable.getClass()) || ComparisonFailureData.isAssertionError(cause != null ? cause.getClass() : null)) [ FD ]
Line_4 $$ final Throwable throwable = failure.getException()-->Line_7 $$ doAddFailure(description, throwable)[ FD ]
Line_2 $$ public synchronized void testFailure(Failure failure) throws Exception -->Line_3 $$ final Description description = failure.getDescription()[ FD ]
Line_5 $$ final Throwable cause = throwable.getCause()-->Line_6 $$ if (ComparisonFailureData.isAssertionError(throwable.getClass()) || ComparisonFailureData.isAssertionError(cause != null ? cause.getClass() : null)) [ FD ]
Line_3 $$ final Description description = failure.getDescription()-->Line_9 $$ prepareDefectPacket(description, throwable).send()[ FD ]
Line_2 $$ public synchronized void testFailure(Failure failure) throws Exception -->Line_4 $$ final Throwable throwable = failure.getException()[ FD ]
Line_6 $$ if (ComparisonFailureData.isAssertionError(throwable.getClass()) || ComparisonFailureData.isAssertionError(cause != null ? cause.getClass() : null)) -->Line_9 $$ prepareDefectPacket(description, throwable).send()[ CD ]
Line_4 $$ final Throwable throwable = failure.getException()-->Line_9 $$ prepareDefectPacket(description, throwable).send()[ FD ]
Line_2 $$ public synchronized void testFailure(Failure failure) throws Exception -->Line_6 $$ if (ComparisonFailureData.isAssertionError(throwable.getClass()) || ComparisonFailureData.isAssertionError(cause != null ? cause.getClass() : null)) [ CD ]
Line_4 $$ final Throwable throwable = failure.getException()-->Line_5 $$ final Throwable cause = throwable.getCause()[ FD ]
Line_6 $$ if (ComparisonFailureData.isAssertionError(throwable.getClass()) || ComparisonFailureData.isAssertionError(cause != null ? cause.getClass() : null)) -->Line_7 $$ doAddFailure(description, throwable)[ CD ]
Line_2 $$ public synchronized void testFailure(Failure failure) throws Exception -->Line_4 $$ final Throwable throwable = failure.getException()[ CD ]
Line_2 $$ public synchronized void testFailure(Failure failure) throws Exception -->Line_3 $$ final Description description = failure.getDescription()[ CD ]
Line_3 $$ final Description description = failure.getDescription()-->Line_7 $$ doAddFailure(description, throwable)[ FD ]
