Line_0 $$ Entry-->Line_2 $$ //217
public class func [ CD ]
Line_2 $$ //217
public class func -->Line_3 $$ public void _failOver(String serverHost, int serverPort, String databasePath, String dbSubPath, String replicatedDb) [ CD ]
Line_3 $$ public void _failOver(String serverHost, int serverPort, String databasePath, String dbSubPath, String replicatedDb) -->Line_4 $$ util.DEBUG(connectionURL)[ CD ]
Line_3 $$ public void _failOver(String serverHost, int serverPort, String databasePath, String dbSubPath, String replicatedDb) -->Line_5 $$ Connection conn = DriverManager.getConnection(connectionURL)[ CD ]
Line_5 $$ Connection conn = DriverManager.getConnection(connectionURL)-->Line_5 $$ DriverManager.getConnection(connectionURL)[ CD ]
Line_3 $$ public void _failOver(String serverHost, int serverPort, String databasePath, String dbSubPath, String replicatedDb) -->Line_6 $$ util.DEBUG("failOver Unexpectedly connected as: " + connectionURL)[ CD ]
