Line_14 $$ List<String> rs = (List<String>) res.get("rs")-->Line_17 $$ assertEquals("Bar", rs.get(1))[ FD ]
Line_3 $$ ResultSet resultSet = mock(ResultSet.class)-->Line_18 $$ verify(resultSet).close()[ FD ]
Line_2 $$ public void testStoredProcedureWithResultSetMapped() throws Exception -->Line_9 $$ given(callableStatement.getMoreResults()).willReturn(false)[ CD ]
Line_12 $$ StoredProcedureWithResultSetMapped sproc = new StoredProcedureWithResultSetMapped(dataSource)-->Line_13 $$ Map<String, Object> res = sproc.execute()[ FD ]
Line_3 $$ ResultSet resultSet = mock(ResultSet.class)-->Line_5 $$ given(resultSet.getString(2)).willReturn("Foo", "Bar")[ FD ]
Line_14 $$ List<String> rs = (List<String>) res.get("rs")-->Line_16 $$ assertEquals("Foo", rs.get(0))[ FD ]
Line_2 $$ public void testStoredProcedureWithResultSetMapped() throws Exception -->Line_10 $$ given(callableStatement.getUpdateCount()).willReturn(-1)[ CD ]
Line_2 $$ public void testStoredProcedureWithResultSetMapped() throws Exception -->Line_14 $$ List<String> rs = (List<String>) res.get("rs")[ CD ]
Line_2 $$ public void testStoredProcedureWithResultSetMapped() throws Exception -->Line_16 $$ assertEquals("Foo", rs.get(0))[ CD ]
Line_2 $$ public void testStoredProcedureWithResultSetMapped() throws Exception -->Line_8 $$ given(callableStatement.getResultSet()).willReturn(resultSet)[ CD ]
Line_13 $$ Map<String, Object> res = sproc.execute()-->Line_14 $$ List<String> rs = (List<String>) res.get("rs")[ FD ]
Line_2 $$ public void testStoredProcedureWithResultSetMapped() throws Exception -->Line_13 $$ Map<String, Object> res = sproc.execute()[ CD ]
Line_2 $$ public void testStoredProcedureWithResultSetMapped() throws Exception -->Line_6 $$ given(callableStatement.execute()).willReturn(true)[ CD ]
Line_3 $$ ResultSet resultSet = mock(ResultSet.class)-->Line_8 $$ given(callableStatement.getResultSet()).willReturn(resultSet)[ FD ]
Line_2 $$ public void testStoredProcedureWithResultSetMapped() throws Exception -->Line_18 $$ verify(resultSet).close()[ CD ]
Line_14 $$ List<String> rs = (List<String>) res.get("rs")-->Line_15 $$ assertEquals(2, rs.size())[ FD ]
Line_2 $$ public void testStoredProcedureWithResultSetMapped() throws Exception -->Line_7 $$ given(callableStatement.getUpdateCount()).willReturn(-1)[ CD ]
Line_2 $$ public void testStoredProcedureWithResultSetMapped() throws Exception -->Line_17 $$ assertEquals("Bar", rs.get(1))[ CD ]
Line_2 $$ public void testStoredProcedureWithResultSetMapped() throws Exception -->Line_3 $$ ResultSet resultSet = mock(ResultSet.class)[ CD ]
Line_2 $$ public void testStoredProcedureWithResultSetMapped() throws Exception -->Line_15 $$ assertEquals(2, rs.size())[ CD ]
Line_2 $$ public void testStoredProcedureWithResultSetMapped() throws Exception -->Line_4 $$ given(resultSet.next()).willReturn(true, true, false)[ CD ]
Line_3 $$ ResultSet resultSet = mock(ResultSet.class)-->Line_4 $$ given(resultSet.next()).willReturn(true, true, false)[ FD ]
Line_2 $$ public void testStoredProcedureWithResultSetMapped() throws Exception -->Line_11 $$ given(connection.prepareCall("[ CD ]
Line_2 $$ public void testStoredProcedureWithResultSetMapped() throws Exception -->Line_12 $$ StoredProcedureWithResultSetMapped sproc = new StoredProcedureWithResultSetMapped(dataSource)[ CD ]
Line_2 $$ public void testStoredProcedureWithResultSetMapped() throws Exception -->Line_5 $$ given(resultSet.getString(2)).willReturn("Foo", "Bar")[ CD ]
