Line_2 $$ public void testTestConnection() throws Exception -->Line_5 $$ final Exception error = myRepository.createCancellableConnection().call()[ CD ]
Line_2 $$ public void testTestConnection() throws Exception -->Line_4 $$ myRepository.setPassword("illegal password")[ CD ]
Line_5 $$ final Exception error = myRepository.createCancellableConnection().call()-->Line_6 $$ assertNotNull(error)[ FD ]
Line_2 $$ public void testTestConnection() throws Exception -->Line_6 $$ assertNotNull(error)[ CD ]
Line_5 $$ final Exception error = myRepository.createCancellableConnection().call()-->Line_7 $$ assertTrue(error.getMessage().contains("Unauthorized"))[ FD ]
Line_2 $$ public void testTestConnection() throws Exception -->Line_3 $$ assertNull(myRepository.createCancellableConnection().call())[ CD ]
Line_2 $$ public void testTestConnection() throws Exception -->Line_7 $$ assertTrue(error.getMessage().contains("Unauthorized"))[ CD ]
